### ISSUE TITLE
Вопросы по запуску Futag

### ISSUE THREAD

**Issue by hpkit** [ispras/Futag#11]
1. Провел подготовку:
myprog.auto_build()
myprog.analyze()

2. Сгенерил таргеты:
g.gen_targets()

-- [Futag] Fuzz-driver has been compiled successfully
-- [Futag] Result of compiling: 42 of 703 fuzz-driver(s)

Что означает 42, что собрались 42 из 703 ?
В каталоге futag-fuzz-drivers 695 подкаталогов и 1 файл.
В части каталогов есть файлы с расширением .out, из запуск приводит к одному из результатов:
- выводу сообщения об утечки памяти и прерыванию работы
- выводу сообщения о падении процесса
- нормальной работе libfuzzer и выводу статистики его работы на экран

4. Фаззинг
f.fuzz()
В обычном случае приводит к сообщению:
============ FINISH ============

Если пробовать издеваться над содержимым каталога futag-fuzz-drivers, оставив в нем несколько подкаталогов с содержимым в котором есть файл с расширением .out , то какое то время выдается, что осуществляется фаззинг и сохраняются его результаты в формате svres

Применимо ли использование вашего проекта не для библиотеки, а для приложения ? На сколько я понимаю обертка создается для конкретной функции и Futag собирает все зависимости для неё. Т.е. нет особых противоречий и всё должно работать. Я прав ?

**Comment by thientc** [comment]
> 1. Провел подготовку:
>    myprog.auto_build()
>    myprog.analyze()
> 2. Сгенерил таргеты:
>    g.gen_targets()
> 
> -- [Futag] Fuzz-driver has been compiled successfully -- [Futag] Result of compiling: 42 of 703 fuzz-driver(s)
> 
> Что означает 42, что собрались 42 из 703 ? В каталоге futag-fuzz-drivers 695 подкаталогов и 1 файл. В части каталогов есть файлы с расширением .out, из запуск приводит к одному из результатов:
> 
> * выводу сообщения об утечки памяти и прерыванию работы
> * выводу сообщения о падении процесса
> * нормальной работе libfuzzer и выводу статистики его работы на экран
> 

Futag считает сколько сгенерированных оберток (*.c) и сколько из низ скомпилированных (*.out).
C помощью Fuzzer.fuzz() вы можете задавать опции, такие как: totaltime, timeout, leak (true/false) и т.д..
Об утечке памяти нужно добавить еще проверку.

> 4. Фаззинг
>    f.fuzz()
>    В обычном случае приводит к сообщению:
>    ============ FINISH ============
> 
> Если пробовать издеваться над содержимым каталога futag-fuzz-drivers, оставив в нем несколько подкаталогов с содержимым в котором есть файл с расширением .out , то какое то время выдается, что осуществляется фаззинг и сохраняются его результаты в формате svres
> 
При анализе результата фаззинга учитывается совпадение трасс, трассы по разным путям сохраняются в файл svres чтобы посмотреть в Svace.

> Применимо ли использование вашего проекта не для библиотеки, а для приложения ? На сколько я понимаю обертка создается для конкретной функции и Futag собирает все зависимости для неё. Т.е. нет особых противоречий и всё должно работать. Я прав ?

Futag выполняет анализ зависимостей при сборке пакета/бибиотеки/программы и сохраняет результат в json-файлы. Затем с помощью python-пакета генерируются фаззинг-обертки для найденных функций. При компиляции оберток Futag ищет статистический ахив (*.a) в скомпилированной библиотеке чтобы ликовать. Эта схема будет работать с приложениями, только нужно что-то добавить чтобы все сработало автоматически.

**Comment by hpkit** [comment]
Буду ждать развития проекта : )

**Comment by hpkit** [comment]
Как я понял более менее собираются только те цели, в который нет других функций, кроме той которая подвергается фаззингу. В каталоге Futag-buld ряд файлов с расширением .new говорят, о том что в момент сборки исходные тексты заголовочных файлов подвергаются изменениям. Какого они рода ?

Я пытался решить проблему линковки c ошибкой "неопределённая ссылка на "функцию которая подвергается фазингу" добавлением заголовка с указанной функцией, что в свою очередь приводит к порождению новый неопределенных ссылок. Пытался так же в строку сборки добавлять .a библиотеку, которая содержит фаззируемую функцию, но получаю еще больший шквал ошибок линковки. Можете подскать в какую сторону копать ?

**Comment by thientc** [comment]
Для правильной сборки фаззинг-оберток нужно знать строку компиляции файла, который содержит целевую функцию. Эта строка включается в файл futag-analysis-result.json в папке futag-analysis, можете там посмотреть.
