### ISSUE TITLE
Проблема сборки

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#12]
`100%] Building CXX object utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o`
`In file included from .../Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.cc:15:`
`.../Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h: In function ‘void AddRange(std::vector<T>*, T, T, int)’:`
`.../Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:30: error: ‘numeric_limits’ is not a member of ‘std’`
`   17 |   static const T kmax = std::numeric_limits<T>::max();`
`      |                              ^~~~~~~~~~~~~~`
`.../Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:46: error: expected primary-expression before ‘>’` `token`
`   17 |   static const T kmax = std::numeric_limits<T>::max();`
`      |                                              ^`
`.../Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:49: error: ‘::max’ has not been declared; did you mean 'std::max'?`
`   17 |   static const T kmax = std::numeric_limits<T>::max();`
`      |                                                 ^~~`
`      |                                                 std::max`
`In file included from /usr/include/c++/11/algorithm:62,`
                 `from .../Futag/custom-llvm/llvm/utils/benchmark/include/benchmark/benchmark.h:175,`
                 `from .../Futag/custom-llvm/llvm/utils/benchmark/src/internal_macros.h:4,`
                 `from ...//Futag/custom-llvm/llvm/utils/benchmark/src/check.h:8,`
                 `from .../Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:6,`
                 `from .../Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.cc:15:`
`/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here`
` 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)`
`      |     ^~~`
`make[2]: *** [utils/benchmark/src/CMakeFiles/benchmark.dir/build.make:90:` `utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:163662: utils/benchmark/src/CMakeFiles/benchmark.dir/all] Error 2`
`make: *** [Makefile:156: all] Error 2`

Ошибка сборки. Ubuntu 22.04 x86_64

**Comment by thientc** [comment]
У меня пока только машины c Ubuntu 16, 18 и 20. Проверю на 22.

**Comment by thientc** [comment]
@mimicria

**Comment by thientc** [comment]
Проблема со сборкой Futag на Ubuntu22 связывается с функцией benchmark. Эту проблему можно решить путем отключения этой фунции: 
**Work around:**
Добавить в строку сборки параметр 
`-DLLVM_INCLUDE_BENCHMARKS=OFF`

Строка сборки в файле build/build.sh или custom-llvm/build.sh после добавления:

`cmake  -G "Unix Makefiles" -DLLVM_BUILD_TESTS=OFF -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$futag_install_folder -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DLLVM_INCLUDE_BENCHMARKS=OFF  -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DLLVM_EXTERNAL_PROJECTS="clang;compiler-rt;" -DLLVM_EXTERNAL_CLANG_SOURCE_DIR=$custom_llvm/clang  -DLLVM_EXTERNAL_COMPILER_RT_SOURCE_DIR=$custom_llvm/compiler-rt $custom_llvm/llvm
`
Если проблема решится, то закрывайте ее пожалуйста. @CourteousSleet @mimicria

**Comment by mimicria** [comment]
> Добавить в строку сборки параметр
> `-DLLVM_INCLUDE_BENCHMARKS=OFF`

@thientc у меня проблема решилась

**Comment by CourteousSleet** [comment]
Проблема решена
