### ISSUE TITLE
Ошибки санитайзера при сборке пакета

### ISSUE THREAD

**Issue by morgonf** [ispras/Futag#13]
Предлагаю убрать из обязательных параметров компилятора санитайзеры.
В процессе тестирования пакета пакета luajit (https://github.com/tarantool/luajit), столкнулся с ошибками санитайзера на этапе сборки.  Использовав метод народного тыка, было обнаружено что сборка без сайнитайзера проходит успешно, после чего был отредактирован файл preprocessor.py, в части "self.flags = "-fsanitize=address -g -O0" и далее процесс прошел без ошибок. 

На сколько необходимо осуществлять сборку именно с санитайзерами?

**Comment by DmitryJustDmitry** [comment]
Сделать санитайзеры обязательным я предлагал в районе одного из первых Issue.
Разве что я предлагал сделать это настраиваемой опцией - чтобы в параметрах futag была возможность добавить опции сборки с типовыми санитайзерами, или отключить, что будет полезно в данном случае.

**Comment by morgonf** [comment]
Возможность добавить опции сборки присутствует, но конкретно этот санитайзер вписан в код продукта.
Так же санитайзеры применяются при сборке фаззинг целей.

**Comment by thientc** [comment]
Добавлю опцию о санитайзерах.

**Comment by thientc** [comment]
> Предлагаю убрать из обязательных параметров компилятора санитайзеры. В процессе тестирования пакета пакета luajit (https://github.com/tarantool/luajit), столкнулся с ошибками санитайзера на этапе сборки. Использовав метод народного тыка, было обнаружено что сборка без сайнитайзера проходит успешно, после чего был отредактирован файл preprocessor.py, в части "self.flags = "-fsanitize=address -g -O0" и далее процесс прошел без ошибок.
> 
> На сколько необходимо осуществлять сборку именно с санитайзерами?

При сборке luajit с санитайзером возникла утечка памяти, можно ее отключить путем задать значение окружающей среды:

`export ASAN_OPTIONS="detect_leaks=0"
`

**Comment by thientc** [comment]
Теперь можно [задавать опцию ](https://github.com/ispras/Futag/blob/main/%D0%98%D0%B3%D1%80%D0%B0%D1%82%D1%8C-%D1%81-Futag.md)со санитайзерами. Данная проблема закрыта.
