### ISSUE TITLE
undefined reference при сборке цели

### ISSUE THREAD

**Issue by morgonf** [ispras/Futag#14]
Futag'ом была сгенерированна фаззинг-цель:
```
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

int LLVMFuzzerTestOneInput(uint8_t * Fuzz_Data, size_t Fuzz_Size)
{
    if (Fuzz_Size < sizeof(int)) return 0;
    uint8_t * pos = Fuzz_Data;
    //GEN_VAR_FUNCTION
    lua_State * L = luaL_newstate();
    //GEN_BUILTIN
    int firstline;
    memcpy(&firstline, pos, sizeof(int));
    pos += sizeof(int);
    //FUNCTION_CALL
    pushline(L ,firstline );
    //FREE
    return 0;
}
```
В процессе штатной работы Futag цель не собирается. При попытке сбора цели, с помощью команды приведённой в файле, компилятор выдаёт ошибку:
```
/home/user/luajit/futag-fuzz-drivers/pushline/pushline1/pushline1.c:12:5: error: use of undeclared identifier 'lua_State'
    lua_State * L = luaL_newstate();
    ^
/home/user/luajit/futag-fuzz-drivers/pushline/pushline1/pushline1.c:12:17: error: use of undeclared identifier 'L'
    lua_State * L = luaL_newstate();
                ^
/home/user/luajit/futag-fuzz-drivers/pushline/pushline1/pushline1.c:12:21: warning: implicit declaration of function 'luaL_newstate' is invalid in C99 [-Wimplicit-function-declaration]
    lua_State * L = luaL_newstate();
                    ^
/home/user/luajit/futag-fuzz-drivers/pushline/pushline1/pushline1.c:18:5: warning: implicit declaration of function 'pushline' is invalid in C99 [-Wimplicit-function-declaration]
    pushline(L ,firstline );
    ^
/home/user/luajit/futag-fuzz-drivers/pushline/pushline1/pushline1.c:18:14: error: use of undeclared identifier 'L'
    pushline(L ,firstline );
```
Поиск в коде исследуемого ПО показал, что "lua_State" объявляется в нескольких заголовочных файлах: lj_obj.h, lua.h, lj_memprof.h. Если вручную добавить заголовочный файл к сгененированной цели, то эта ошибка исчезнет. Однако появится другая:
```
/usr/bin/ld: /tmp/pushline1-efaeca.o: in function `LLVMFuzzerTestOneInput':
/home/user/luajit/futag-fuzz-drivers/pushline/pushline1/pushline1.c:18: undefined reference to `pushline'
/usr/bin/ld: /home/user/luajit/futag-fuzz-drivers/pushline/pushline1/pushline1.c:18: undefined reference to `pushline'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```
Функция pushline, та самая для которой эта цель и генеририровалась объявляется и используется в файле "luajit.c".

Таким образом получается что Futag некорректно сформировал цель и не может задействовать её про фаззинге.

**Comment by DmitryJustDmitry** [comment]
Приведи, пожалуйста, конкретный репозиторий (коммит), на котором тестируешься.

**Comment by morgonf** [comment]
Осуществляю тестирование интерпретатора LuaJIT из репозитория https://github.com/tarantool/luajit (LuaJIT 2.1.0-beta3)

**Comment by hpkit** [comment]
самый простой вариант это скопировать код функции pushline и разместить её над `int LLVMFuzzerTestOneInput(uint8_t * Fuzz_Data, size_t Fuzz_Size)
{...}`

**Comment by morgonf** [comment]
Добавлю архив с файлами где объявляется функция pushline (luajit.c) и со генерированной целью (pushline1.c).
[pushline.tar.gz](https://github.com/ispras/Futag/files/9582501/pushline.tar.gz)

**Comment by thientc** [comment]
Было улучшено подключение заголовочных файлов. Временно закрываю эту проблему, если что можете открыть заново.
