### ISSUE TITLE
Ошибка сборки

### ISSUE THREAD

**Issue by mimicria** [ispras/Futag#17]
Добрый день!
Действую по п.4 (Сборка из исходного кода), при выполнении build.sh получаю ошибку
```
[ 22%] Linking CXX static library ../libLLVMSupport.a
[ 22%] Built target LLVMSupport
make: *** [Makefile:156: all] Ошибка 2

======== End of install script for FUTAG - a fuzzing target automated generator ========
```
Пролистывая чуть назад лог, нахожу красные ошибки:
```
In file included from /home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.cc:15:
/home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h: In function ‘void AddRange(std::vector<T>*, T, T, int)’:
/home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:30: error: ‘numeric_limits’ is not a member of ‘std’
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                              ^~~~~~~~~~~~~~
/home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:46: error: expected primary-expression before ‘>’ token
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                                              ^
/home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:49: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                                                 ^~~
      |                                                 std::max
```

Система Ubuntu 22.04
По тем пакетам, что в требованиях:
cmake version 3.22.1
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Python 3.10.4
pip 22.2.2
zlib 1.2.11
make 4.3

**Comment by DmitryJustDmitry** [comment]
Futag пока что не умеет работать с С++ (соответствующее Issue заведено) - ошибки проявляется на этапе компоновки с С++ `Linking CXX`.

Ждёмс.

**Comment by thientc** [comment]
> Добрый день! Действую по п.4 (Сборка из исходного кода), при выполнении build.sh получаю ошибку
> 
> ```
> [ 22%] Linking CXX static library ../libLLVMSupport.a
> [ 22%] Built target LLVMSupport
> make: *** [Makefile:156: all] Ошибка 2
> 
> ======== End of install script for FUTAG - a fuzzing target automated generator ========
> ```
> 
> Пролистывая чуть назад лог, нахожу красные ошибки:
> 
> ```
> In file included from /home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.cc:15:
> /home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h: In function ‘void AddRange(std::vector<T>*, T, T, int)’:
> /home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:30: error: ‘numeric_limits’ is not a member of ‘std’
>    17 |   static const T kmax = std::numeric_limits<T>::max();
>       |                              ^~~~~~~~~~~~~~
> /home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:46: error: expected primary-expression before ‘>’ token
>    17 |   static const T kmax = std::numeric_limits<T>::max();
>       |                                              ^
> /home/user/Futag/custom-llvm/llvm/utils/benchmark/src/benchmark_register.h:17:49: error: ‘::max’ has not been declared; did you mean ‘std::max’?
>    17 |   static const T kmax = std::numeric_limits<T>::max();
>       |                                                 ^~~
>       |                                                 std::max
> ```
> 
> Система Ubuntu 22.04 По тем пакетам, что в требованиях: cmake version 3.22.1 gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0 Python 3.10.4 pip 22.2.2 zlib 1.2.11 make 4.3

Совпадает [с проблемой ](https://github.com/ispras/Futag/issues/12). Сборка было проверена на системах Ubuntu 16, 18 и 20, пока разбираюсь с Ubuntu22.
