### ISSUE TITLE
Предложения по улучшению readme

### ISSUE THREAD

**Issue by DmitryJustDmitry** [ispras/Futag#2]
На основе сообщения https://t.me/sdl_dynamic/3172

Начал тестировать futag, возникло несколько вопросов/предложений по документации и собственно по инструменту:

1. Добавить в 2.1 явно установку python3-pip. Он потребуется для установки futag.

2. Опечатки - цифры 1-2-3 в наименованиях библиотек в 2.1.

3.  В строке pip install /path/to/python/futag-package/dist/futag-0.1.tar.gz путь не сразу понятен - ../Futag/src/python/futag-package/dist/futag-0.1.tar.gz было бы читабельнее.

4. В 3 в "Запуск сборки..." предлагается чуть подробнее расписать два параметра Builder (хотя бы в том объеме, в котором они собственно в [compiler.py](http://compiler.py/) закомментированы). В частности, первый параметр должен указывать конкретно на каталог build, полученный на прошлом шаге.

5. В 3, в "Генерация..." путь "/path/to/futag/package/" для единообразия предлагается заменить на упомянутый чуть выше "../../futag-llvm-package".

6. Мелочь, но всё таки - от фразы "Успешно скомпилированные цели находятся в каталоге futag-fuzz-drivers. Каждый драйвер находится внутри своей поддиректории." ожидаешь, что в поддиректориях будут лежать именно что бинарники. А не исходные тексты, которые успешно скомпилировал futag, но все равно нужно компилировать самому. Предлагаю фразу уточнить. Кстати, опционально, почему бы рядом не прикладывать именно бинарники собранные? Например с address, undefined? И аналогично - coverage? 

7. После сборки json-c у меня получилось около 50ти драйверов. Большинство из них представлены как каталог с именем драйвера, в котором лежит один единственный файл исходных текстов драйвера с расширением .c. Однако:

7.1. В некоторых каталогах (процентов 15 от общего числа) дополнительно лежит большой файл .out (3-4 мегабайта), в котором похоже лежат пострипанные символы. Это зачем? Это баг (НДВ :)) или фича? Опишите, пожалуйста, в readme, если это фича.

7.2. Для ряда драйверов файлов-исходников получилось сильно больше чем 1 (в частности для json-c для драйвера json_object_to_fd их больше 10ти). Я понимаю, что это видимо завязано на перегрузки конструкторов, в т. ч. конструкторов объектов параметров. Но можно ли чуть подробнее раскрыть данный вопрос в документации (в частности глубина перебора вариантов конструкторов)? В том числе фраза "Каждый драйвер находится внутри своей поддиректории." получается частично неверной - в одной поддиректории может быть 1-N драйверов.

**Comment by morgonf** [comment]
По приведённому выше описанию, предлагаю повторно скорректировать [README.md](https://github.com/ispras/Futag#readme)
В раздел 2 "Установка":
1) предлагаю скорректировать зависимости:
CMake  >=3.13.4 Makefile/workspace generator
GCC >=7.1.0 C/C++ compiler1
python >=3.6 Automated test suite2
zlib >=1.2.3.4 Compression library3
GNU Make 3.79, 3.79.1 Makefile/build processor4
2) предлагаю заменить "futag-llvm-package/python-package/futag-1.1.tar.gz" на " ../Futag/src/python/futag-package/dist/futag-1.1.tar.gz", как было озвучено ранее

В раздел 3 "ИспользованиЕ":
1) для Builder на мой взгляд, нужно указать все ключи которые можно добавить при написании функции.
2) раз уж гайд на русском, предлагаю перевести комментарии:
"package futag must be already installed" == "предварительно должен быть установлен пакет futag-<версия>.tar.gz"
"path to the futag-llvm-package" =="путь к директории "futag-llvm-package"
"library root" == "путь к директории содержащей исходные кода исследуемого ПО"
и т.п. 
3) Аналогично расписать ключи для Generator

Так же считаю что п.7.1 и 7.2 таки нуждаются в пояснении

**Comment by thientc** [comment]
> 7.1. В некоторых каталогах (процентов 15 от общего числа) дополнительно лежит большой файл .out (3-4 мегабайта), в котором похоже лежат пострипанные символы. Это зачем? Это баг (НДВ :)) или фича? Опишите, пожалуйста, в readme, если это фича.
> 
Попробуйте посмотреть бинарники с objdump:
`objdump -d a.out`

**Comment by DmitryJustDmitry** [comment]
Закрываем, документация улучшена, вопросы разобраны.
