### ISSUE TITLE
Добавить тестовый скрипты

### ISSUE THREAD

**Issue by DmitryJustDmitry** [ispras/Futag#24]
В каталог Futag помещать сразу шаблоны двух простых скриптов анализа и генерации. Чтобы нужно было только подставить каталог к исходникам и можно было запускать.

**Comment by morgonf** [comment]
Предлагаю сразу добавлять документированные шаблоны скриптов запуска, пример во вложении.
[futag_test.zip](https://github.com/ispras/Futag/files/9607937/futag_test.zip)
