### ISSUE TITLE
Запуск сборок проектов futag-tests в контейнерах

### ISSUE THREAD

**Issue by DmitryJustDmitry** [ispras/Futag#30]
Некоторые пакеты требуют доустановки окружения.
Некоторым пакетам может мешать уже ранее установленное окружение пакетов других версий.

Предлагается проработать вопрос реализации запуска сборки и анализа каждого пакета в отдельном контейнере. Тогда в скрипте prepare.sh можно будет минимально настраивать окружение под каждый конкретный пакет.

Эта задача, даже если будет принята, в любом случае ФОНОВОГО приоритета, поскольку не связана с основной бизнес-логикой Futag.

**Comment by thientc** [comment]
The Docker containers are added to testing repository https://github.com/thientc/Futag-tests
