### ISSUE TITLE
Совместимость с afl-clang-fast

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#41]
Хотелось бы попробовать получить бинари для afl-fuzz, но для цели afl-clang-fast потребовал -fPIE, а с этим флагом вся сборка цели падает. Как бы с этим справиться?

**Comment by thientc** [comment]
Флаги можете задавать при компиляции оберток, если он пустой то добавим -fPIE для afl-clang-fast  и -fsanitize=fuzzer для LibFuzzer.

```python
generator.compile_targets(
  4, # количество задач при сборке
  # keep_failed=True, # сохранить не скомпилированные цели
  # extra_include="-DHAVE_CONFIG_H", # дополнительные параметры при сборке библиотеки,
  # extra_dynamiclink="-lz", # системные библиотеки для линковки
  # flags="-ferror-limit=1", # значение по умолчанию: ""
)
