### ISSUE TITLE
New information to issues #42

### ISSUE THREAD

**Issue by MoJl4yH** [ispras/Futag#43]
По пути _Futag/src/python/futag-package/dist/futag-1.2.2.tar.gz_ лежит не тот _generation.py_. При установке с помощью _pip install Futag/src/python/futag-package/dist/futag-1.2.2.tar.gz_ возникает проблема:
```
Traceback (most recent call last):
  File "analyze.py", line 22, in <module>
    generator.compile_targets(
  File "/home/negoro/.local/lib/python3.8/site-packages/futag/generator.py", line 2703, in compile_targets
    compiler_flags_aflplusplus += " -fPIE"
UnboundLocalError: local variable 'compiler_flags_aflplusplus' referenced before assignment
```
Исправляется заменой инсталлированного generation.py на generation.py который лежит в исходниках (_Futag/src/python/futag-package/src/futag_)

---------
При генерации обвязок под AFLPLUSPLUS все равно возникает ошибка (пробовал с PAM, так и с json-c)
```
-- [Futag] ERROR on target  json_object_array_add126 :
 gcc: error: : No such file or directory
gcc: error: : No such file or directory
```

В качестве workaroud попробовал сделать символическую ссылку на компилятор afl-clang-lto, установленный в систему, проблема аналогичная.
Система и скрипты сборки аналогичные issues #42.

С генерацией для libfuzzer все ок:
```
-- [Futag] collecting result ...
-- [Futag] Result of compiling: 1157 fuzz-driver(s)
```

**Comment by thientc** [comment]
Вы скачали отсюда: https://github.com/ispras/Futag/releases/tag/latest ?

**Comment by MoJl4yH** [comment]
> Вы скачали отсюда: https://github.com/ispras/Futag/releases/tag/latest ?

Там update 4 часа назад, с утра сделал git clone репозитория. По поводу билда для afl, если запускать команду которая лежит в файле .c (для которого генерируется обвязка), то все собирается.

```
/home/negoro/Fuzzing/Futag/futag-llvm/AFLplusplus/usr/local/bin/afl-clang-fast -fsanitize=address -g -O0 -I/home/negoro/Garbage/json-c/ -I/home/negoro/Garbage/json-c/.futag-build/  /home/negoro/Garbage/json-c/futag-fuzz-drivers/failed/json_object_equal/json_object_equal175/json_object_equal175.c -o /home/negoro/Garbage/json-c/futag-fuzz-drivers/failed/json_object_equal/json_object_equal175/json_object_equal175.out -Wl,--start-group /home/negoro/Garbage/json-c/.futag-install/lib/libjson-c.a /home/negoro/Garbage/json-c/.futag-build/libjson-c.a -Wl,--end-group
afl-cc++4.04c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC_PLUGIN-DEFAULT
afl-gcc-pass ++4.02c by <oliva@adacore.com>
[*] Inline instrumentation at ratio of 100% in non-hardened mode.
/home/negoro/Garbage/json-c/futag-fuzz-drivers/failed/json_object_equal/json_object_equal175/json_object_equal175.c:22:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   22 | main() {
      | ^~~~
[+] Instrumented 14 locations (non-hardened mode, inline, ratio 100%).
```

**Comment by MoJl4yH** [comment]
Судя по всему, проблема в том, что при билде скриптом он путь до директории _.futag-fuzz-driver_ начинает с точки, а по факту она начинается без точки, просто  _.futag-fuzz-driver_. И соответственно в сам файл .c он пишет правильную команду для сборки.

**Comment by thientc** [comment]
Да, я забыл обновил архив, поэтому у вас возможно не тот рабочий питон-пакет. Попробуй тот, который в архив пожалуйста!

> Судя по всему, проблема в том, что при билде скриптом он путь до директории _.futag-fuzz-driver_ начинает с точки, а по факту она начинается без точки, просто _.futag-fuzz-driver_. И соответственно в сам файл .c он пишет правильную команду для сборки.

Вы прав, до сборки все цели сохраняются в скрытой папке .futag-fuzz-driver (с точкой) и после сборки я собираю успешно скомпилированные цели в папку futag-fuzz-driver/succeeded/ (без точки), а нескомпилированные в failed. Пытался поменять путь в самом файле кода но видимо где-то неправильно.
