### ISSUE TITLE
Ошибка при сборке цели с CMakeLists.txt

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#47]
Скрипт для сборки успешно завершился, а при компиляции целей получается ошибка, что бы это могло быть?
````
-- [Futag] Try to generate fuzz-driver for function:  <имя_функции>
Traceback (most recent call last):
  File "/build//run_futag.py", line 13, in <module>
    g.compile_targets()
  File "/home/имя_пользователя/.local/lib/python3.10/site-packages/futag/generator.py", line 2752, in compile_targets
    current_include.append("-I" + i + "/")
TypeError: can only concatenate str (not "PosixPath") to str
````

**Comment by thientc** [comment]
Видимо у вас старый пакет Футаг. Попробуйте переустановить Питон-пакет:
```bash
pip install futag-llvm/python-package/futag-1.3.tar.gz
```
Архив можете загрузить здесь: https://github.com/ispras/Futag/releases/tag/1.3

**Comment by CourteousSleet** [comment]
С новым пакетом уже при сборке ошибка, а не компиляции
````
 -- [Futag]: Getting info from file <file>...
Traceback (most recent call last):
  File "/home/user/build/build.py", line 10, in <module>
    build_agent.analyze()
  File "/home/user/.local/lib/python3.10/site-packages/futag/preprocessor.py", line 736, in analyze
    "gen_return_type": function_list[func]["gen_return_type"],
KeyError: 'gen_return_type'
````

**Comment by thientc** [comment]
> С новым пакетом уже при сборке ошибка, а не компиляции
> 
> ```
>  -- [Futag]: Getting info from file <file>...
> Traceback (most recent call last):
>   File "/home/user/build/build.py", line 10, in <module>
>     build_agent.analyze()
>   File "/home/user/.local/lib/python3.10/site-packages/futag/preprocessor.py", line 736, in analyze
>     "gen_return_type": function_list[func]["gen_return_type"],
> KeyError: 'gen_return_type'
> ```

Попробуй обновленный пакет пожалуйста! (
https://github.com/ispras/Futag/releases/tag/1.3
