### ISSUE TITLE
FUTAG, glibc и Debian

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#49]
Из-за того, что в FUTAG используется готовый llvm, на системах Debian из-за более старой версии glibc clang не работает.

Возникла потребность научить FUTAG работать с системным clang'ом..

Хотелось бы получить инструкцию по работе FUTAG с системным llvm'ом, и возможной доработки FUTAGA'а в случае если это проблематично или невозможно...

В идеале хотелось бы получить поддержку LLVM_CONFIG или какого-то ее аналога. А сам FUTAG чтобы дальше у него всю информацию об LLVM получал.

**Comment by thientc** [comment]
> Из-за того, что в FUTAG используется готовый llvm, на системах Debian из-за более старой версии glibc clang не работает.
> 
> Возникла потребность научить FUTAG работать с системным clang'ом..
> 

Для удобства Futag предоставляется отдельный пакет но Вы можете собрать с исходного кода. Посмотрите [2.3. Сборка и установка из исходного кода](https://github.com/ispras/Futag#2-установка). До версии 1.3 Futag собирается с llvm 12, 13 и 14. 

> Хотелось бы получить инструкцию по работе FUTAG с системным llvm'ом, и возможной доработки FUTAGA'а в случае если это проблематично или невозможно...
> 
> В идеале хотелось бы получить поддержку LLVM_CONFIG или какого-то ее аналога. А сам FUTAG чтобы дальше у него всю информацию об LLVM получал.

можете задавать путем:
`export LLVM_CONFIG=futag-llvm/bin/llvm-config
`

**Comment by CourteousSleet** [comment]
Спасибо. Для уточнения: до версии 1.3 значит, что 1.3 я не смогу использовать с llvm 12-13 или включительно до 1.3?

**Comment by thientc** [comment]
Я просто удалил файлы для сборки с LLVM12 и LLVM13, можете восстановить и попробовать. Если что я верну эти файлы в новом коммите.

**Comment by CourteousSleet** [comment]
Спасибо
