### ISSUE TITLE
Уменьшение объема Futag-дистрибутива

### ISSUE THREAD

**Issue by DmitryJustDmitry** [ispras/Futag#5]
Развертывание Futag по readme-инструкции в настоящий момент требует скачивания около 2х ГБ исходников (в основном LLVM). Даже в достаточно быстрой сети это процесс не моментальный, особенно если CI будет выстроен в парадигме сборки каждого окружения "с нуля" (такие примеры нам известны). Можно ли как-то уменьшить объём скачиваемого дистрибутива? 

Также, как вариант, дополнительно подготовить и выложить публично пресобранный контейнер, который явно должен быть меньше по размеру?

**Comment by thientc** [comment]
Добавил папку custom-llvm и скрипт для сборки, обновите проект пожалуйста. Размер проекта сейчас ~ 150МБ. По поводу контейнера по-позже добавлю.
