### ISSUE TITLE
Флаги libFuzzer

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#56]
Если возникла потребность запустить цель с такими флагами:
````
./target.out Corpus/ -detect_leaks=1 -print_final_stats=1 -use_counters=1 -reload=1 -print_coverage=1
````
Можно ли их как-то отправить внутрь Fuzzer() как строку флагов или можно использовать только опции, указаннные в параметрах?

**Comment by thientc** [comment]
Пока передавать в Futag.Fuzzer только такие параметры:
https://github.com/ispras/Futag/blob/fe5d165b3d3d30713f50bc13bded8859042e8baa/src/python/futag-package/src/futag/fuzzer.py#L30

Могу добавить дополнительный аргумент для пользовательских параметров в новом коммите.

**Comment by CourteousSleet** [comment]
Было бы здорово

**Comment by thientc** [comment]
Добавил, проверьте!
