### ISSUE TITLE
Сделать режим многопоточной генерации драйверов

### ISSUE THREAD

**Issue by DmitryJustDmitry** [ispras/Futag#7]
Запускаю futag на процессоре с 32 ядрами.

Хотелось бы иметь возможность распараллеливания процесса порождения драйверов. Иначе процесс генерации выполняется долго, но при этом задействуется только одно ядро - соответственно генерация растягивается надолго.

Это не критический функционал - futag в целом не предназначен для постоянных перезапусков на одной и той же кодовой базе, так что скорее это инструмент однократного применения, и его можно оставить и на ночь.

Однако если такую возможность можно ввести (по умолчанию задействование всех доступных ядер, либо принудительно указывать количество) это точно не будет лишним.

**Comment by thientc** [comment]
Собираюсь выпустить Футаг-фаззер в следующей версии и там будут многопоточная генерация, многопоточный фаззинг.

**Comment by thientc** [comment]
Кстати при сборке библиотеки уже есть возможность задать количество потоков, посмотрите пожалуйста аргумент processes в классе Builder: src/python/futag-package/README.md

**Comment by thientc** [comment]
Код обновил, почитайте документацию чтобы узнать как задавать аргументы для этого режима.
