### ISSUE TITLE
Нейминг целей.

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#82]
Возможно ли сделать опциональной возможность изменения нейминга целей? Так как мне необходимо иметь имя цели как PQdb.5 вместо PQdb5, например.

**Comment by thientc** [comment]
А примерно как вы задаете такую опцию?

**Comment by CourteousSleet** [comment]
Не совсем понял вопрос. Как бы я задал? Ну например:
````
build_agent = Builder(
    "{}".format(futag_path),
    "{}".format(libpq_path),
    clean=True,
    processes=8,
    **delimiter="."**
)
````
