### ISSUE TITLE
Более расширенная диагностика при отсутсвии AFL++

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [ispras/Futag#89]
При сборке и установке FUTAG'а был по ошибке пропущен шаг сборки AFL++, т.е. запуск `buildAFLplusplus.sh`

После этого при запуске сборки с FUTAG, процесс сборки стал выводить достаточно бессмысленное диагностическое сообщение: `-- [Futag]: Incorrect path to FUTAG llvm package` Которое было по сути не верно. Путь был правильным, а вот AFL++ не был собран.

В результате было потрачено лишнее время на разбирательство с проблемой некорректного пути.

Предложение в этом месте сначала проверить корректность пути к по факту наличия файлов директории `futag-llvm` на которые не оказывает влияние процесс сборки, и отдельно проверить был ли собран AFL++.

**Comment by thientc** [comment]
Принято!

**Comment by thientc** [comment]
> При сборке и установке FUTAG'а был по ошибке пропущен шаг сборки AFL++, т.е. запуск `buildAFLplusplus.sh`
> 
> После этого при запуске сборки с FUTAG, процесс сборки стал выводить достаточно бессмысленное диагностическое сообщение: `-- [Futag]: Incorrect path to FUTAG llvm package` Которое было по сути не верно. Путь был правильным, а вот AFL++ не был собран.
> 
> В результате было потрачено лишнее время на разбирательство с проблемой некорректного пути.
> 
> Предложение в этом месте сначала проверить корректность пути к по факту наличия файлов директории `futag-llvm` на которые не оказывает влияние процесс сборки, и отдельно проверить был ли собран AFL++.

Проверьте!

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> Проверьте!
