### ISSUE TITLE
Проблема с генерацией цели.

### ISSUE THREAD

**Issue by CourteousSleet** [ispras/Futag#9]
При попытке начать компиляцию целей с помощью FUTAG получил ошибку вида:
```bash
-- [Futag] Fuzz-driver for function:  pg_strip_crlf  generated!
-- [Futag] Fuzz-driver for function:  pg_clean_ascii  generated!
Traceback (most recent call last):
  File "generate.py", line 14, in <module>
    g.compile_targets()
  File "/home/ian/.local/lib/python3.8/site-packages/futag/generator.py", line 615, in compile_targets
    [x for x in (self.install_path / "include" ).iterdir() if x.is_dir()]
  File "/home/ian/.local/lib/python3.8/site-packages/futag/generator.py", line 615, in <listcomp>
    [x for x in (self.install_path / "include" ).iterdir() if x.is_dir()]
  File "/usr/lib/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ian/Work/FUZ-48/libpq-standalone/futag-install/include'
```

Хотел бы уточнить, с чем это может быть связано (сборка была успешно произведена)?

1. Python скрипты были использованы те же, что в doc файле ["https://github.com/ispras/Futag/tree/main/src/python/futag-package"](https://github.com/ispras/Futag/tree/main/src/python/futag-package). То есть сначала ```auto_build()``` или ```build_cmake()```, далее ```analyze()```, а затем ```gen_targets()``` и ```compile_targets()```.

2. Проект был взят открытый с GitLab (собирается через CMake): ["https://gitlab.com/sabelka/libpq-standalone/-/tree/main/"](https://gitlab.com/sabelka/libpq-standalone/-/tree/main/)

3. Ошибка появлялась на этапе компиляции. Сборка проходила успешно.

**Comment by thientc** [comment]
Спасибо, я знаю в чем проблема,  поправлю и обновлю код.

**Comment by thientc** [comment]
Код обновлен, можете скачать [pre-release пакет](https://github.com/ispras/Futag/releases/tag/pre-release) чтобы попробовать.

**Comment by CourteousSleet** [comment]
-- Error: loading json from file: /home/jjjj/jjj/postgres/futag-analysis/declaration-QhPIkrcMrSCIdqQK.futag-function-analyzer

При сборке с использованием последней версии FUTAG таких сообщений об ошибке выходит более 20, влияет ли это на работу генератора целей?

**Comment by thientc** [comment]
> -- Error: loading json from file: /home/jjjj/jjj/postgres/futag-analysis/declaration-QhPIkrcMrSCIdqQK.futag-function-analyzer
> 
> При сборке с использованием последней версии FUTAG таких сообщений об ошибке выходит более 20, влияет ли это на работу генератора целей?
> 
Нет, не влияет.
> Внутри самих файлов указано только null.

Точно, эти файлы сгенерированы при анализу но информации в них нет. Я поправлю и добавлю в новой версии. Сейчас жду результат тестов и выпущу.

**Comment by thientc** [comment]
@CourteousSleet  попробовали новую версию? Можем вместе поискать ошибки?

**Comment by CourteousSleet** [comment]
@thientc Попробовал собрать новую версию из исходного кода.

`
[ 25%] Linking CXX static library ../libLLVMSupport.a
[ 25%] Built target LLVMSupport
make: *** [Makefile:156: all] Error 2

======== End of install script for FUTAG - a fuzzing target automated generator ========
`
Сборка проводилась на Ubuntu 22.04 x86_64.
