### ISSUE TITLE
Сборка с покрытием и без санитайзеров.

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [ispras/Futag#91]
Выяснилось, что в собрке с покрытием включены так же и санитайзеры. 

Выяснилось это потому что при фаззинге мы в нашей системе подавляем сообщения об утечках памяти установив переменную окружения `ASAN_OPTIONS=detect_leaks=0`. А вот при построении покрытия у нас это опция не включается, потому что сборка с покрытием во всех остальных проектах у нас не содержит инструментации от санитайзеров. Что в общем-то логично...

В результате при построении покрытия профаженных целей у нас начинает срабатывать LeakSanitizer, что крайне не радостно. 

Сборку с покрытием мы осуществляем командой `g.compile_targets(keep_failed=True, keep_original=True, coverage=True)` 

Хотелось бы в этом случае получать сборку без лишней инструментации чтобы санитайзеры не давали ненужных срабатываний.

**Comment by thientc** [comment]
Чтобы включить "detect_leaks" и отключить "coverage" при фаззингу можете задавать опцию: 
``` python
fuzzer = Fuzzer( # модуль для фаззинга
    FUTAG_PATH,
    fuzz_driver_path="json-c-json-c-0.16-20220414/futag-fuzz-drivers/", 
...
    leak=True,
    coverage=False, #по умолчанию эта опция отключена
...
)
```
