### ISSUE TITLE
Управление Futag без питона

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [ispras/Futag#92]
В нашей системе автоматизации фаззинг-тестирования нету кода написанного на питоне и нету питон-программистов. 

Очень бы хотелось иметь возможность управлять FUTAG'ом без написания какого либо кода на питоне. Через json- или yaml- конфиги, опции командной строки или переменные окружения.

Чтение и тем более написание кода на python для нас является неудобным и неприятным занятием. Я был бы очень рад свести к нулю количество питоновского кода в моей системе автоматизации, но к сожалению футаг мне этого не позволяет. Хотелось бы таки добиться полного отсутствие чужеродного языка в проекте...

**Comment by thientc** [comment]
Питон используется в данном проекте для обработки результатов анализа, генерации фаззинг-оберток, и обработки результата фаззинга.
После установки/сборки вам придется только написать простой скрипт для анализа тестируемой библиотеки, например:
```python
from futag.preprocessor import *

FUTAG_PATH = "/home/futag/Futag-tests/futag-llvm/"
lib_path = "path/to/library/source/code"
build_test = Builder(
    FUTAG_PATH,
    lib_path,
    clean=True, # удалить все папки сгенерированные Futag-ом перед сборкой
    # intercept=True, # запуск компиляции с инструментом "intercept" для анализа compile_command.json
    # processes=4, # количество задач при сборке
    # build_ex_params="--with-openssl --with-mhash" # дополнительные параметры при сборке библиотеки
)
build_test.auto_build()
build_test.analyze()
```
В нем только параметры для запуска анализа, проще никак )
Ко сожалению, переписать Питон-модили в баш или другой язык не могу.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Я не предлагаю что-то переписывать.

Я предлагаю сделать интерфейс управления независимым от языка реализации...

Конфигурация на python'е автоматически означает, что у нас в проекте оказывается дополнительный язык, которого раньше не было. Как архитектор, по множеству оснований, я обязан такой ситуации избегать.

Вот замени python на ocaml или tcl и посмотри насколько тебе захочется иметь дело с таким проектом и почему. С python'ом та же история, просто ты его знаешь.
